#!/bin/bash

if [ "$1" = "build" ]; then
  npx tailwindcss -c ./tailwind.config.js -i ./styles/input.css -o ./styles/output.css --minify
  trunk build --release --public-url yousearch-client/ --dist docs
elif [ "$1" = "dev" ]; then
  trunk serve -d docs
elif [ "$1" = "tailwind" ]; then
  npx tailwindcss -w -c ./tailwind.config.js -i ./styles/input.css -o ./styles/output.css
else
  echo "Usage: $0 [build|watch|dev]"
fi
